---
- name: check for existing install...
  become: yes
  stat:
    path: '{{ keycloak_install_dir }}'
  changed_when: False
  register: keycloak_binary

- when: not keycloak_binary.stat.exists
  block:
    - name: download tgz
      become: yes
      become_user: root
      get_url:
        url: '{{ keycloak_tgz_url }}'
        dest: /tmp/{{ keycloak_tgz }}
        checksum: '{{ keycloak_checksum }}'
        mode: 0644
    - name: unarchive
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ keycloak_tgz }}
        dest: '{{ keycloak_parent_install_dir }}'
        creates: '{{ keycloak_install_dir }}'
  always:
    - name: cleanup...
      become: yes
      become_user: root
      file:
        path: /tmp/{{ keycloak_tgz }}
        state: absent

- name: link
  become: yes
  become_user: root
  file:
    src: '{{ keycloak_install_dir }}'
    dest: '{{ keycloak_link_dir }}'
    state: link

- name: add to path
  become: yes
  with_items:
    - f: keycloak.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'

- name: Create Keycloak User
  tags: ['add-user']
  shell: "/usr/local/keycloak/bin/add-user-keycloak.sh -u {{ user }} -p {{ password }}"

- name: keycloak systemd setup
  tags: ['keycloak']
  template:
    owner: root
    group: root
    mode: 0644
    src: keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
  notify:
    - reload systemd